version: '3.8'

volumes:
  mysql-vol:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer:4.8.1
    container_name: adminer-container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql-container

  api:
    build: './api'
    container_name: node-container
    restart: always
    ports:
      - 5030:5030
    volumes:
      - ./api:/home/node/app
    depends_on:
      - mysql

  web:
    image: php:8.0-apache
    container_name: php-container
    restart: always
    ports:
      - 8888:80
    depends_on:
      - api
    volumes:
      - ./website:/var/www/html
