version: '3.8'

volumes:
  mysql-vol:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  api:
    build: './api'
    container_name: node-container
    restart: always
    ports:
      - 5030:5030
    volumes:
      - ./api:/home/node/app
    depends_on:
      - mysql

  web:
    image: php:8.0-apache
    container_name: php-container
    restart: always
    ports:
      - 8888:80
    depends_on:
      - api
    volumes:
      - ./website:/var/www/html
